image: python:3.7

stages:
- publish

wheel:
  stage: publish
  before_script:
  - pip install poetry
  - poetry install
  script:
  - poetry build -f wheel
  - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
  only:
  - tags
